---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
    channel: rubocop-0-90
    config:
      file: .rubocop_cc.yml

ratings:
  paths:
  - "**.rb"
exclude_paths:
- spec/
- lib/skylight/vendor/
