cache:
  paths:
    - vendor/bundle
    - cc-test-reporter

variables:
  SKYLIGHT_EXT_STRICT: "false"
  SKYLIGHT_REQUIRED: "true"
  SKYLIGHT_ENABLE_TRACE_LOGS: "true"
  SKYLIGHT_TEST_DIR: "/tmp"
  RAILS_ENV: "development"
  EMBEDDED_HTTP_SERVER_TIMEOUT: "30"
  WORKER_SPAWN_TIMEOUT: "15"
  COVERAGE_DIR: $CI_PROJECT_DIR/coverage

.run_tests: &run_tests
  before_script:
    - gem install bundler
    - |
      if [[ "$BUNDLE_GEMFILE" =~ "rails-4.2" ]]; then
        gem install bundler -v "< 2"
        export BUNDLER_VERSION=1
      fi
  script:
    - pushd skylight-core
    - bundle install --path ../vendor/bundle
    - bundle exec rake
    - SKYLIGHT_DISABLE_AGENT=true bundle exec rake
    - popd
    - bundle install --path vendor/bundle
    - bundle exec rake
    - SKYLIGHT_DISABLE_AGENT=true bundle exec rake
  after_script:
    - if [ -f $COVERAGE_DIR/.resultset.json ]; then mv $COVERAGE_DIR/.resultset.json $COVERAGE_DIR/coverage-$CI_JOB_ID.json; fi
  artifacts:
    paths:
      - $COVERAGE_DIR/coverage-$CI_JOB_ID.json

.install_codeclimate: &install_codeclimate
  before_script:
    - if [[ ! -f cc-test-reporter ]]; then curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter; fi
    - chmod +x ./cc-test-reporter

stages:
  - sanity
  - test
  - wrapup

codeclimate_setup:
  only:
    variables:
      - $COVERAGE == "true"
  stage: sanity
  image: ruby:2.6
  <<: *install_codeclimate
  script:
    - ./cc-test-reporter before-build

sanity:
  <<: *run_tests
  stage: sanity
  image: ruby:2.6
  variables:
    BUNDLE_GEMFILE: $CI_PROJECT_DIR/gemfiles/Gemfile.rails-5.2.x

ruby23-rails42:
  <<: *run_tests
  stage: test
  image: ruby:2.3
  variables:
    BUNDLE_GEMFILE: $CI_PROJECT_DIR/gemfiles/Gemfile.rails-4.2.x

ruby26-rails42:
  <<: *run_tests
  stage: test
  image: ruby:2.6
  variables:
    BUNDLE_GEMFILE: $CI_PROJECT_DIR/gemfiles/Gemfile.rails-4.2.x

ruby23-rails52:
  <<: *run_tests
  stage: test
  image: ruby:2.3
  variables:
    BUNDLE_GEMFILE: $CI_PROJECT_DIR/gemfiles/Gemfile.rails-5.2.x

ruby26-rails50:
  <<: *run_tests
  stage: test
  image: ruby:2.6
  variables:
    BUNDLE_GEMFILE: $CI_PROJECT_DIR/gemfiles/Gemfile.rails-5.0.x

ruby26-rails51:
  <<: *run_tests
  stage: test
  image: ruby:2.6
  variables:
    BUNDLE_GEMFILE: $CI_PROJECT_DIR/gemfiles/Gemfile.rails-5.1.x

ruby26-rails-edge:
  <<: *run_tests
  stage: test
  allow_failure: true
  image: ruby:2.6
  variables:
    BUNDLE_GEMFILE: $CI_PROJECT_DIR/gemfiles/Gemfile.rails-edge

ruby23-sinatra14:
  <<: *run_tests
  stage: test
  image: ruby:2.3
  variables:
    BUNDLE_GEMFILE: $CI_PROJECT_DIR/gemfiles/Gemfile.sinatra-1.4.x

ruby26-sinatra14:
  <<: *run_tests
  stage: test
  image: ruby:2.6
  variables:
    BUNDLE_GEMFILE: $CI_PROJECT_DIR/gemfiles/Gemfile.sinatra-1.4.x

ruby23-sinatra20:
  <<: *run_tests
  stage: test
  image: ruby:2.3
  variables:
    BUNDLE_GEMFILE: $CI_PROJECT_DIR/gemfiles/Gemfile.sinatra-2.0.x

ruby26-sinatra20:
  <<: *run_tests
  stage: test
  image: ruby:2.6
  variables:
    BUNDLE_GEMFILE: $CI_PROJECT_DIR/gemfiles/Gemfile.sinatra-2.0.x

ruby26-sinatra-edge:
  <<: *run_tests
  stage: test
  allow_failure: true
  image: ruby:2.6
  variables:
    BUNDLE_GEMFILE: $CI_PROJECT_DIR/gemfiles/Gemfile.sinatra-edge

ruby23-grape:
  <<: *run_tests
  stage: test
  image: ruby:2.3
  variables:
    BUNDLE_GEMFILE: $CI_PROJECT_DIR/gemfiles/Gemfile.grape

ruby26-grape:
  <<: *run_tests
  stage: test
  image: ruby:2.6
  variables:
    BUNDLE_GEMFILE: $CI_PROJECT_DIR/gemfiles/Gemfile.grape

ruby26-grape013:
  <<: *run_tests
  stage: test
  image: ruby:2.6
  variables:
    BUNDLE_GEMFILE: $CI_PROJECT_DIR/gemfiles/Gemfile.grape
    GRAPE_VERSION: "~> 0.13.0"

ruby26-grape110:
  <<: *run_tests
  stage: test
  image: ruby:2.6
  variables:
    BUNDLE_GEMFILE: $CI_PROJECT_DIR/gemfiles/Gemfile.grape
    GRAPE_VERSION: "~> 1.1.0"

ruby26-grape120:
  <<: *run_tests
  stage: test
  image: ruby:2.6
  variables:
    BUNDLE_GEMFILE: $CI_PROJECT_DIR/gemfiles/Gemfile.grape
    GRAPE_VERSION: "~> 1.2.0"

ruby26-grape-edge:
  <<: *run_tests
  stage: test
  allow_failure: true
  image: ruby:2.6
  variables:
    BUNDLE_GEMFILE: $CI_PROJECT_DIR/gemfiles/Gemfile.grape
    GRAPE_VERSION: edge

ruby26-rails42-tilt:
  <<: *run_tests
  stage: test
  image: ruby:2.6
  variables:
    BUNDLE_GEMFILE: $CI_PROJECT_DIR/gemfiles/Gemfile.rails-4.2.x
    TILT_VERSION: 1.4.1

ruby26-sinatra14-sequel:
  <<: *run_tests
  stage: test
  image: ruby:2.6
  variables:
    BUNDLE_GEMFILE: $CI_PROJECT_DIR/gemfiles/Gemfile.sinatra-1.4.x
    SEQUEL_VERSION: 4.34.0

ruby26-rails42-mongo:
  <<: *run_tests
  stage: test
  image: ruby:2.6
  services:
    - mongo:3.4-jessie
  variables:
    BUNDLE_GEMFILE: $CI_PROJECT_DIR/gemfiles/Gemfile.rails-4.2.x
    TEST_MONGO_INTEGRATION: "true"
    MONGO_HOST: mongo

ruby26-rails42-mongoid:
  <<: *run_tests
  stage: test
  image: ruby:2.6
  services:
    - mongo:3.4-jessie
  variables:
    BUNDLE_GEMFILE: $CI_PROJECT_DIR/gemfiles/Gemfile.rails-4.2.x
    TEST_MONGO_INTEGRATION: "true"
    MONGO_HOST: mongo
    MONGOID_VERSION: "~> 4.0"

ruby26-rails42-elasticsearch:
  <<: *run_tests
  stage: test
  image: ruby:2.6
  services:
    - elasticsearch:5-alpine
  variables:
    BUNDLE_GEMFILE: $CI_PROJECT_DIR/gemfiles/Gemfile.rails-4.2.x
    TEST_ELASTICSEARCH_INTEGRATION: "true"
    ELASTICSEARCH_URL: "http://elasticsearch:9200"

ruby26-rails51-sidekiq4:
  <<: *run_tests
  stage: test
  image: ruby:2.6
  variables:
    BUNDLE_GEMFILE: $CI_PROJECT_DIR/gemfiles/Gemfile.rails-5.1.x
    SIDEKIQ_VERSION: 4.2.10

ruby26-rails51-sidekiq-none:
  <<: *run_tests
  stage: test
  image: ruby:2.6
  variables:
    BUNDLE_GEMFILE: $CI_PROJECT_DIR/gemfiles/Gemfile.rails-5.1.x
    SIDEKIQ_VERSION: "none"

ruby26-rails42-ams83:
  <<: *run_tests
  stage: test
  image: ruby:2.6
  variables:
    BUNDLE_GEMFILE: $CI_PROJECT_DIR/gemfiles/Gemfile.rails-4.2.x
    AMS_VERSION: "~> 0.8.3"

ruby26-rails42-ams95:
  <<: *run_tests
  stage: test
  image: ruby:2.6
  variables:
    BUNDLE_GEMFILE: $CI_PROJECT_DIR/gemfiles/Gemfile.rails-4.2.x
    AMS_VERSION: "~> 0.9.5"

ruby26-rails42-ams-edge:
  <<: *run_tests
  stage: test
  allow_failure: true
  image: ruby:2.6
  variables:
    BUNDLE_GEMFILE: $CI_PROJECT_DIR/gemfiles/Gemfile.rails-4.2.x
    AMS_VERSION: edge

ruby-head-rails52:
  <<: *run_tests
  stage: test
  allow_failure: true
  image: rubocophq/ruby-snapshot:latest
  variables:
    BUNDLE_GEMFILE: $CI_PROJECT_DIR/gemfiles/Gemfile.rails-5.2.x

codeclimate:
  only:
    variables:
      - $COVERAGE == "true"
  stage: wrapup
  image: ruby:2.6 # can probably use a lighter image, but this one is already cached.
  <<: *install_codeclimate
  script:
    - mkdir -p formatted_coverage
    - find coverage -name *.json | xargs -I % ./cc-test-reporter format-coverage -t simplecov -o formatted_coverage/% %
    - ./cc-test-reporter sum-coverage formatted_coverage/**/*.json
    - ./cc-test-reporter upload-coverage
