language: ruby
cache: bundler
sudo: false

env:
  global:
    - SKYLIGHT_ENABLE_TRACE_LOGS=true
    - SKYLIGHT_REQUIRED=true
    - SKYLIGHT_TEST_DIR=/tmp
    - RAILS_ENV=development
    - EMBEDDED_HTTP_SERVER_TIMEOUT=30
    - WORKER_SPAWN_TIMEOUT=15
  matrix:
    # The first one is intentionally empty in order to run without any extra env vars
    -
    - SKYLIGHT_DISABLE_AGENT=true

rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.2.0

gemfile:
  - gemfiles/Gemfile.rails-3.0.x
  - gemfiles/Gemfile.rails-3.2.x
  - gemfiles/Gemfile.rails-4.0.x
  - gemfiles/Gemfile.rails-4.1.x
  - gemfiles/Gemfile.sinatra-1.2.x
  - gemfiles/Gemfile.sinatra-1.3.x
  - gemfiles/Gemfile.sinatra-edge
  # Declared manually in the matrix include due to Mongoid compat issues
  # - gemfiles/Gemfile.rails-edge

matrix:
  exclude:
    # Rails 4.0+ requires Ruby 2.0+
    - rvm: 1.9.2
      gemfile: gemfiles/Gemfile.rails-4.0.x
    - rvm: 1.9.2
      gemfile: gemfiles/Gemfile.rails-4.1.x
    - rvm: 1.9.2
      gemfile: gemfiles/Gemfile.rails-edge

    # Seems unlikely anyone will be running these combos
    # If we want to support, we need to fix failing tests
    - rvm: 2.2.0
      gemfile: gemfiles/Gemfile.rails-3.0.x
    - rvm: 2.2.0
      gemfile: gemfiles/Gemfile.rails-3.2.x

    # We don't need to test so many disabled combinations
    - rvm: 1.9.3
      env: SKYLIGHT_DISABLE_AGENT=true
    - rvm: 2.0.0
      env: SKYLIGHT_DISABLE_AGENT=true
    - rvm: 2.1.5
      env: SKYLIGHT_DISABLE_AGENT=true

  include:
    # Mongoid requires ActiveModel ~> 4.0
    - rvm: 2.2.0
      env: SKIP_MOPED=true
      gemfile: gemfiles/Gemfile.rails-edge
    - rvm: 2.2.0
      env:
        - SKIP_MOPED=true
        - SKYLIGHT_DISABLE_AGENT=true
      gemfile: gemfiles/Gemfile.rails-edge
    # Test old Tilt version (with Rails since Sinatra doesn't like old Tilt)
    - rvm: 2.2.0
      env:
        - TILT_VERSION=1.1
      gemfile: gemfiles/Gemfile.rails-4.1.x
    # Test old Sequel version
    - rvm: 2.2.0
      env:
        - SEQUEL_VERSION=3.12.0
      gemfile: gemfiles/Gemfile.sinatra-1.3.x


  allow_failures:
    # Testing edge is nice, but it probably shouldn't kill the build
    - gemfile: gemfiles/Gemfile.sinatra-edge
    - gemfile: gemfiles/Gemfile.rails-edge

notifications:
  webhooks:
    urls: https://tilde.slack.com/services/hooks/travis?token=N5Dc2tov6aTfOjXK1VOXlxiS
    on_success: change
    on_failure: always
