language: ruby

script: bundle exec rspec -cfs spec/

env:
  global:
    - SKYLIGHT_ENABLE_TRACE_LOGS=true
    - RAILS_ENV=development

rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - jruby

gemfile:
  - gemfiles/Gemfile.rails-3.0.x
  - gemfiles/Gemfile.rails-3.2.x
  - gemfiles/Gemfile.rails-4.0.x
# - gemfiles/Gemfile.rails-edge

matrix:
  exclude:
    # As far as I can tell, Magnum wants the env, public doesn't
    - rvm: 1.9.2
      gemfile: gemfiles/Gemfile.rails-4.0.x
      env:
        - SKYLIGHT_ENABLE_TRACE_LOGS=true
        - RAILS_ENV=development
    - rvm: 1.9.2
      gemfile: gemfiles/Gemfile.rails-4.0.x

# TODO: We may want to bring back rails-edge and add to allow_failures list

notifications:
  campfire:
    rooms:
      - secure: "IRhdYUI6TCUTma3JTkv1NSrLuQIuCEyCKjKHVf2hl8VwmxridYfit5ewLs2F\n3kzk0Owh6lsM0eSyIygTGyT+5xIplZgk7N/p8ImvbqvTuNylqmmv7xoBaxKF\nTFmQaXHkSiVOF30EP67uF6zbENMT/n9+IpaXX45wrdu1XCP5SX4="
    on_success: change
    on_failure: always
  webhooks:
    urls: https://tilde.slack.com/services/hooks/travis?token=N5Dc2tov6aTfOjXK1VOXlxiS
    on_success: change
    on_failure: always